import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const geistSans = Geist({
  variable: '--font-geist-sans',
  weight: ['400', '500', '600', '800'],
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className='flex justify-between items-center flex-nowrap gap-4 max-w-6xl mx-auto px-4 pt-10'>
          <Link href='/' className='font-bold text-4xl'>
            Books
          </Link>
          <ul className='flex list-style-none justify-end items-center gap-4'>
            <li>
              <Link
                href='/books'
                className='font-semibold text-xl pb-1 border-b-[2px] border-transparent hover:border-zinc-500 hover:transition-colors hover:ease-in-out hover:duration-250 duration-250 transition-colors text-zinc-500'
              >
                Book List
              </Link>
            </li>
            <li>
              <Link
                href='/search'
                className='font-semibold text-xl pb-1 border-b-[2px] border-transparent hover:border-zinc-500 hover:transition-colors hover:ease-in-out hover:duration-250 duration-250 transition-colors text-zinc-500'
              >
                Search
              </Link>
            </li>
            <li>
              <Link
                href='/stats'
                className='font-semibold text-xl pb-1 border-b-[2px] border-transparent hover:border-zinc-500 hover:transition-colors hover:ease-in-out hover:duration-250 duration-250 transition-colors text-zinc-500'
              >
                Stats
              </Link>
            </li>
          </ul>
        </header>
        <div className='max-w-6xl mx-auto px-4 py-20'>
          <main className=''>{children}</main>
        </div>
      </body>
    </html>
  )
}
